language: ruby
bundler_args: --without development
script: "PUPPET_TEST_VASH=1 bundle exec rake spec --trace"
notifications:
  email: false
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
